### ISSUE TITLE
次回公演のみ応募可能にする

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#1]
次に行われる公演にのみ応募可能にします。
このルールに従わないリクエストについては`403`を返すようにします。

**Comment by Cj-bc** [comment]
個人的補足:
  抽選は、その公演の前の公演（2番目の枠なら1番目の時）に行います。（これは依頼）
  なので、今やっている公演の次の公演のみしか受け付けないわけです。

**Comment by coord-e** [comment]
次回公演は応募不可にするみたいな話があった気がするので保留、委員会に聞く

**Comment by Cj-bc** [comment]
結局、以下の通りの時間のみ応募が可能となりました。

```markdown
|=======|=========|
| 第2公演 | 9:20 ~ 9:50 |
| 第3公演 | 10:45 ~ 11:45 |
| 第4公演 | 12:10 ~ 12:40 |
| 第5公演 | 13:35 ~ 14:05 |
```

**Comment by coord-e** [comment]
このテーブルみたいなのも #30 で作ったので早くマージできるようにやっていきますね

**Comment by Cj-bc** [comment]
よろしくです（markdown表記対応してるかと思ったらダメだった）
ってことは今できるものがないな...orz

**Comment by Cj-bc** [comment]
status_codeは403とありますが、`draw`系では同じような条件に対して400を出しています。
これは揃えたほうがいい..??

**Comment by Cj-bc** [comment]
- [ ] `test_apply`
- [ ] `test_apply_time_invalid`
- [ ] `apply.yaml`

**Comment by Cj-bc** [comment]
少し仕様を変えました。

* 創作展の時間外の時 -> `No lotteries are supplied`
* 創作展中、応募の時間外 -> `you can't apply to this lottery`

**Comment by Cj-bc** [comment]
PR作成 #96

**Comment by coord-e** [comment]
#96 Merged, closing
