### ISSUE TITLE
`Authenicate`スペルミスがある

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#101]
Step 2: 問題
============

ただ単のスペルミスですっ☆ (便乗

どうなってしまうか:
-------------------

  * `authenicate`正しくは`authenticate`

**Comment by Cj-bc** [comment]
えこれある...??
`git grep -l 'authenicate'`したけど何も出なかった...

**Comment by Cj-bc** [comment]
close by merging of #114
