### ISSUE TITLE
`/lotteries/{id}/draw`がちょっとどころではなくおかしい（条件分岐にミスがある）

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#107]
Step 2: 問題
============

どうなっているか:
-------------------

該当箇所: `backend/api/routes/api.py L201`
```python
def draw_lottery(idx):
           ...
    lottery = Lottery.query.get(idx)
            ...
    try:
        # Get time index with current datetime
        index = get_draw_time_index()
           ...

    if index != idx:   # <----------------------------- 該当部分ココ
        return not_acceptable_resp, 400
```

`index`は`lottery.index`、`idx`は`lottery.id`なのでこの二つを比較するのは本来意味を持たないと思います。
正しくは以下のようになるべきです

```python
if index != lottery.index:
```

**Comment by Cj-bc** [comment]
バグということで修正しますがこの修正に関して特に問題ないよね？？ @coord-e

**Comment by coord-e** [comment]
なんだこれは...
まずこの状態で落ちるようにテストを書き換え、そのあとにこれを修正する感じでお願いしていいですか

**Comment by Cj-bc** [comment]
あい
自分で他案件のテスト書きながらかなり頭ひねりましたので...ww
とりあえず了解です

**Comment by Cj-bc** [comment]
close by merging of #110
