### ISSUE TITLE
`apply`のエラーレスポンスから、`already done`を削除する

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#117]
Step 1: 目的
============

 * 軽量化及び不要なコードの削除

Step 2: 概要
============

 * #96 のマージにより、応募可能な時間帯を制限することにより、既に終わった`lottery`に応募することは不可能になりました。
 * これは、`aleady done`のレスポンスが目的としていた行為を含んでおり、二重に同じ処理をかけるのはコード的にもよろしくないし、のちのリファクタリングにて混乱を招くだけだと思いました。

関連するコード:
---------------

  ```python
    lottery = Lottery.query.get(idx)
        ...
    if lottery.done:
        return jsonify({"message": "This lottery has already done"}), 400

  ```
タスク:
=======

- [x] 該当部分を削除

**Comment by tamazasa** [comment]
これやると現行の`test_draw_already_done`が落ちるようになります
（`400`が返されるはずが`200`が返る）
問題はテストコードにあるわけですが
_attempt to draw previously drawn lottery._
これを正しく行うテストをするには、前回の`time index`中の応募データをデータベースに追加する必要があります
（「応募時間外の抽選ができない」というテストは別に`test_draw_time_invalid`としてあります）

**Comment by tamazasa** [comment]
ちなみにこのテスト以外のコードは完成済みで
`feature/117-remove-errmsg`にあります

**Comment by tamazasa** [comment]
…宿題が結構残ってるので今後作業時間減るかもしれません
しばらく放置状態になってしまったらすみません
作業はある意味一区切りついているので、どなたか引き継いでいただいて構いません
それが必要になるような事態になるまでには復帰したいと思います

**Comment by Cj-bc** [comment]
そもそも「*応募時間外のlotteryに応募できない*」仕組みがきちんと動いてれば「*終わったlotteryに投票可能になる*」状況は存在し得ない（存在したとすれば、"*応募時間外のlotteryに応募できない*"ようにする仕組みが壊れているから）ので、`test_draw_already_done`自体削除して問題ないと思います。

**Comment by tamazasa** [comment]
テストコードの動作の仕組みがいまいち完全に理解しきれてないのでなんとも言えないのですが
現段階の`test_lottery.py`が`time index`１つのみでテストしているように見えます
前回のtime indexのlotteryに次のtime indexから応募できないことをテストする必要があるように思えているのですが

**Comment by Cj-bc** [comment]
> 前回のtime indexのlotteryに次のtime indexから応募

この部分がいまいちよく分からないです...

**Comment by tamazasa** [comment]
１つ目の応募枠に２つ目の応募時間から応募
実際にそんな変なことをわざわざする人がいるとは思えませんが

**Comment by tamazasa** [comment]
書き方変ですみません

**Comment by tamazasa** [comment]
いま`test_lottery.py`一通り読んで理解しました
失礼しましたm(_ _)m

**Comment by tamazasa** [comment]
件の`test_draw_already_done`削除しました

**Comment by Cj-bc** [comment]
了解です〜
コード増えてるからね、把握するのも大変ですよね...(把握しきれてない人より

**Comment by Cj-bc** [comment]
close with merging of #142
