### ISSUE TITLE
団体応募時、メンバーの他クラス応募を許可するか

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#119]
個人応募の際は、同じ`period`への二つ目の応募は不可能です。
これを踏まえ、団体応募の際の条件として、**全メンバーが誰1人同じ`period`のlotteryへ応募していない**事を追加したいと思います。

これを追加しなかった場合のデメリット：
* 別の人を代表にして、何箇所も応募することができてしまう

---

議論の余地はほぼないとは思いますが、記録的な意味も含めて立てました
@Sakuten/moderator

**Comment by tamazasa** [comment]
こちらに関しては #116 の「応募」の範囲ということで良いのですよね
たしかに明らかに必要なルールですね

**Comment by Cj-bc** [comment]
そうです、完全に #116 の範囲です。
この条件は追加すべきですよね...?w

**Comment by tamazasa** [comment]
個人申込みだってそういうルールになってますし
完全にすべきですね

**Comment by Cj-bc** [comment]
了解です。
それではそういうことにしてここ閉じますね
