### ISSUE TITLE
secret_id => public_id　変換

### ISSUE THREAD

**Issue by tamazasa** [Sakuten/backend#126]
Step 1: 目的
============

 * 当選者発表等

Step 2: 概要
============

 * `secret_id`から`public_id`に変換する

**Comment by Cj-bc** [comment]
これ、エンドポイント名はどうしましょうか。 @Sakuten/moderator 
とりあえず`/to_public`で定義しておきます（のちの変更は容易なので。）

**Comment by Cj-bc** [comment]
メゾットは`POST`...で、いいのかな？？？

**Comment by Cj-bc** [comment]
それと権限の範囲はどうしますか？
`checker`とかそんな感じ？？

**Comment by coord-e** [comment]
GETでお願いします

**Comment by coord-e** [comment]
権限はnormal以上

**Comment by Cj-bc** [comment]
GETということはパスに含める形ですか？

**Comment by Cj-bc** [comment]
決定事項:

* *エンドポイント* : `/public_id/<secret_id>`
* *method*: `GET`
* *権限*: `normal以上`

**Comment by Cj-bc** [comment]
レスポンスの形は
```json
  { "public_id": <public_id> }
```
という形で書いていますがいいですか？ @Sakuten/frontend

**Comment by coord-e** [comment]
~~それが404ならgroup_membersの無効idも404にならねえか？~~任せます

**Comment by coord-e** [comment]
あとそのwas省いていいかも

**Comment by Cj-bc** [comment]
> group_membersの件

は、知らんです。っていうかなんで404じゃないんだっけ？？

> wasいらないと思う

我もそう思う。というか元々入れてなかったんだけども。前入れろって言われた記憶があったのだが…まぁいいや消しとくな

**Comment by Cj-bc** [comment]
PR #136

**Comment by Cj-bc** [comment]
close with mergining of #136
