### ISSUE TITLE
ログインの問題の原因究明を容易にする

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#135]
Step 1: 目的
============

 * ログインできない時原因究明困る

Step 2: 概要
============

 * `production`以外のconfigの時に、ログイン失敗についてログを吐く

**Comment by Cj-bc** [comment]
これでログ吐く必要があるのは以下の通りで大丈夫ですか？？

1. reCAPTCHA認証が失敗した
2. Secret_idが不正だった

@coord-e

**Comment by coord-e** [comment]
はい

**Comment by Cj-bc** [comment]
了解です

**Comment by Cj-bc** [comment]
ちょっと外れますね、pythonのロガー周りが思ったよりも複雑だった...

**Comment by coord-e** [comment]
これ本番までにできます？

**Comment by Cj-bc** [comment]
えと、ごめん #183回りに時間食われるので無理だと思う…
少なくとも私は無理かと

**Comment by Cj-bc** [comment]
[この記事](http://www.subarunari.com/entry/2017/10/07/014911)によると、`DEBUG=False`の際に出力されるログは`error`以上らしいので`error`にするしかない...?

**Comment by Cj-bc** [comment]
@coord-e と話して、作展に間に合わせなくていいとのことになったのでタグ付け

**Comment by shino16** [comment]
問題ないので閉じます
