### ISSUE TITLE
Public IdのところがSecret Idになっている

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#137]
Step 2: 問題
============

https://github.com/Sakuten/backend/blob/9441009344bf1aa47939427910a387a12140c667/api/spec/routes/api/translate_secret_to_public.yml#L17
  
どうなるべきだったのか:
-----------------------

  * `s/secret_id/public_id/`
  * `s/SecretID/PublicID/`

**Comment by Cj-bc** [comment]
close with merging of #143
