### ISSUE TITLE
create_all, drop_allで例外が発生する

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#15]
起動時に上記2関数にて`sqlalchemy.exc.ProgrammingError`が発生します
https://github.com/Sakuten/lottery-backend/blob/3dea388ac9de760368d00ea17550f113bd9e2730/api/app.py#L27
https://github.com/Sakuten/lottery-backend/blob/3dea388ac9de760368d00ea17550f113bd9e2730/api/app.py#L31

現在は握りつぶしていますが全容の解明が求められます

**Comment by Cj-bc** [comment]
確認して見たところ、いまの状態ではエラーが出ていないようです。
何がどう影響したのか不明ですが...

**Comment by coord-e** [comment]
我が握りつぶしてます
