### ISSUE TITLE
Use `app.logger.warning` instead of `app.logger.warn`

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#168]
Step 1: 目的
============

 * `The 'warn' method is deprecated, use 'warning' instead`

Step 2: 概要
============

 * Use `app.logger.warning` instead of `app.logger.warn`

**Comment by Cj-bc** [comment]
branch: feature/168-remove-logger-warn

**Comment by Cj-bc** [comment]
PR: #184

**Comment by Cj-bc** [comment]
close with merging of #184
