### ISSUE TITLE
Public ID の重複に対応

### ISSUE THREAD

**Issue by tamazasa** [Sakuten/backend#182]
Step 1: 目的
============

 *  student, visitorでpublic_idが420個被った
 * secret_idは被っていない

Step 2: 概要
============

 * 正常に応募・抽選・発表ができるようにする

**Comment by tamazasa** [comment]
`feature/public-id-dup`

**Comment by tamazasa** [comment]
pass unit test

**Comment by coord-e** [comment]
https://github.com/Sakuten/backend/blob/010dc5d9f8085932a4f1999ada81410fb3db8edb/cards/id.py#L69

**Comment by tamazasa** [comment]
> [backend/cards/id.py](https://github.com/Sakuten/backend/blob/010dc5d9f8085932a4f1999ada81410fb3db8edb/cards/id.py#L69)
> 
> Line 69 in [010dc5d](/Sakuten/backend/commit/010dc5d9f8085932a4f1999ada81410fb3db8edb)
> 
>  def find_secret_id(ids, public_id):

使われてないし削除しちゃいます
書くにしてもDBのqueryで書いたほうがわかりやすいですし

**Comment by Cj-bc** [comment]
PR: #209 
closed with merging of PR
