### ISSUE TITLE
/public_idで返ってくるpublic IDが数字

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#185]
Step 1: 環境
============

 * Linux coordiserver 4.17.0-3-amd64#1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
 * Sakuten/devenv@22a22738848c07dcea5edb0fdfd1e0b026b84e21
 * Sakuten/frontend@582f517fb881615d7166f51fc50fa1d61867901b
 * Sakuten/backend@807a8944709e11ee00bc966e32689df9cb42f379
  
Step 2: 問題
============

  
どうなってしまうか:
-------------------

  * /public_idで返ってくるpublic IDが数字
  
どうなるべきだったのか:
-----------------------

  * /public_idで返ってくるpublic IDは英数字、つまり3GWYとかそういう。
  
関連するコード:
---------------

https://github.com/Sakuten/backend/blob/807a8944709e11ee00bc966e32689df9cb42f379/api/routes/api.py#L362

https://github.com/Sakuten/backend/blob/807a8944709e11ee00bc966e32689df9cb42f379/cards/id.py#L12

**Comment by coord-e** [comment]
これは実質情報ですが、普段から数字です

https://github.com/Sakuten/backend/blob/807a8944709e11ee00bc966e32689df9cb42f379/api/models.py#L20

**Comment by Cj-bc** [comment]
ええ...なんで....
誰ですかそこ数字にしたの...
... @coord-e お前か...ww
なんでこうしたんやろ..?

**Comment by Cj-bc** [comment]
```python
<X_X>:backend$ pipenv run python
Python 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from api.models import User
>>> User.public_id
<sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x1096634c0>
>>> type(User.public_id
... )
<class 'sqlalchemy.orm.attributes.InstrumentedAttribute'>
>>> user = User(secret_id='sec', public_id='pub', kind='student', authority='normal')
>>> user
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/coju/Desktop/sakuten/devenv/backend/api/models.py", line 26, in __repr__
    return f'<User {encode_public_id(self.public_id)} {authority_str}>'
  File "/Users/coju/Desktop/sakuten/devenv/backend/cards/id.py", line 26, in encode_public_id
    latter_3_num = num_id // (18**3)
TypeError: unsupported operand type(s) for //: 'str' and 'int'
>>> user.public_id
```

そうすると今度はこっちが謎い...
まぁいいや、`Strings`に修正しますね

**Comment by coord-e** [comment]
`encode_`と`decode_`があるしまあ数字で扱った方が速そうだから...

**Comment by coord-e** [comment]
いやModelは変えるなよ？？

**Comment by coord-e** [comment]
そのコードは`User(secret_id='sec', public_id='pub', kind='student', authority='normal')`について`s/'pub'/0/g`であるべきです

**Comment by Cj-bc** [comment]
え、ドユコト...??
`Integer`で扱っているものを文字列で返すの...?
ってか文字列を数字で扱ってるってどういうことなの...??

**Comment by coord-e** [comment]
https://github.com/Sakuten/backend/blob/807a8944709e11ee00bc966e32689df9cb42f379/cards/id.py#L12

**Comment by Cj-bc** [comment]
え、まって前提として、`public_id`は文字列のアレとは違うの...?

**Comment by Cj-bc** [comment]
まじかよ...そういうの早く言えよ...
聞いてないぜそんなん
確かにあることは把握してたけどさ

**Comment by coord-e** [comment]
型からわかる通りModelの中に入っているのは文字列ではないですね

**Comment by coord-e** [comment]
えぇ...言う手段が無い...

**Comment by Cj-bc** [comment]
わけが..わからねぇぜ...
うちらは`public_id`って`4YMY`とかの形が普通やから流石にそのまま処理してると思ってたよ...なんだよそれは...

**Comment by Cj-bc** [comment]
ってかなんで`decode_`と`encode_`があるの？
なぜ数字にした??

**Comment by coord-e** [comment]
うちらがと言うか数字でエンコードにしたの @tamazasa です
理由は知らんがid生成上そっちのが楽だったんだろう

**Comment by coord-e** [comment]
Modelに数字で突っ込んだのは僕
理由は速そうだったから

**Comment by Cj-bc** [comment]
えぇ....
流石にそういうのは明示的に言ってください、わけがわからない...
文字列で与えてるものを数字で扱うなんて狂った発想できるほど頭良くないので...

**Comment by coord-e** [comment]
wiki整備すべきでしたな
んまー修正楽だしいいじゃないすか

**Comment by Cj-bc** [comment]
いいじゃないですかじゃねぇよ...
情報共有はしっかりやってくれよ...
同じような事例が他にもありそうだなおい？？

**Comment by Cj-bc** [comment]
PR: #187

**Comment by Cj-bc** [comment]
close with merging of #187
