### ISSUE TITLE
`/status`で自身のkindが知りたい

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#186]
Step 1: 目的
============

 * checkerと一般で同一のログイン画面を使うとき、
 * ログインした時に自分がcheckerなのかなんなのかわからないので
 * /statusにkindを含めて欲しいです。
 * Use in Sakuten/frontend#89

Step 2: 概要
============

 * UserSchemaにkindを含める

**Comment by Cj-bc** [comment]
PR: #188

**Comment by Cj-bc** [comment]
close with merging of #188
