### ISSUE TITLE
パスワード認証を廃止する

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#21]
現時点では、パスワード&ユーザーネームでのログインになっていますが、本番環境ではIDのみになります。
ので、パスワード認証を廃止しておく必要があります。
尚、パスワードが廃止された後は、入力されたIDがDB上にあればログイン、なければエラーを返すような形>になると考えられます。

**Comment by Cj-bc** [comment]
#41 の前にこちらを決める必要がありそうです。
中身に関して何か意見はありますでしょうか？ @Sakuten/moderator 
又、 #33 より、reCAPTCHAが必要なのでその認証で行おうと思います。
今日の19時までに無いようなら、次の仕様に決定します

```
入力されたIDがDB上にあり、reCAPTCHAを通っていればログイン、なければエラーを返す
```

**Comment by coord-e** [comment]
そうですね

**Comment by Cj-bc** [comment]
#54 がマージされたらclose

**Comment by Cj-bc** [comment]
#54 mergeによりclose
