### ISSUE TITLE
wkhtmltopdfがalpine上で正常に動作しなかった場合の対応

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#211]
* `alpine`上で`wkhtmltopdf`がうまく動かないとの情報がありました。
 * 実際のところどうだかはわかりませんが、動かなかった場合の代行案として、以下の案をあげておきます
    * `Dockerイメージ`を根本的に`alpine`ではないものにする
    * `wkhtmltopdf`以外のツールを使う
    * `PHP`を使って生成する(`FPDF`なる標準モジュールがあるらしい)

どれを取るかは、個別にissue立てして話し合う必要があるかもしれません

**Comment by shino16** [comment]
PDFは使わないのでオッケーです
