### ISSUE TITLE
複数日運用のためにDBリセット

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#227]
Step 2: 問題
============
  
どうなってしまうか:
-------------------

  * `application`や`lottery.done`などが日をまたいでもリセットされず、応募ができなくなる
  
どうなるべきだったのか:
-----------------------

  * それらがリセットされ流べきだった

**Comment by tamazasa** [comment]
`Lottery`に`day`コラムみたいなのを作って、`'first'`と`'second'`みたいなのを設定して`Lottery`2日分初期化しておけばいいのでは

**Comment by shino16** [comment]
これはapplicationをqueryする際に当日のものだけとってきており、.doneも廃止したのでありません
