### ISSUE TITLE
生徒会室プリンタで`/render_results`が表示できない

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#237]
Step 2: 問題
============

再現のための手順:
-----------------

生徒会室PCをWi-Fiにつなげてhttps://api.sakuten.jp/render_resultsにアクセス
  
どうなってしまうか:
-------------------

しばらく「読み込み中」になったのち
「api.sakuten.jpからの応答時間が長すぎます」とエラーが出る
  
どうなるべきだったのか:
-----------------------

  * ちゃんと表示

**Comment by Cj-bc** [comment]
wifiが遅いわけではない...?
自分のところからはアクセスできました

**Comment by tamazasa** [comment]
僕のPCも同じWi-Fiでつなげてるんですが、すぐ表示されます
Wi-Fi自体がそこまで遅いということはないはずです

**Comment by tamazasa** [comment]
生徒会室PCのWi-Fiハードウェアがアな可能性はありますかね

**Comment by tamazasa** [comment]
Google Chromeのバージョンの問題がぱっと思いつきます

**Comment by shino16** [comment]
今年できたからもういいね
