### ISSUE TITLE
repがキャンセルしていないのにキャンセルされた

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#241]
Step 2: 問題
============

再現のための手順:
-----------------

  1. _____
  2. _____
  3. _____
  
どうなってしまうか:
-------------------

  * キャンセルしていないのにキャンセル処理がされたらしい
  
どうなるべきだったのか:
-----------------------

  * キャンセル処理が行われないべきだった

  
関連するコード:
---------------

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by Cj-bc** [comment]
これ、結果的にキャンセルされたという認識で良いですか？

**Comment by Cj-bc** [comment]
rep含め3人での団体応募で、repのみキャンセルされたパターンが多いらしいです

**Comment by shino16** [comment]
これ2019は発生しなかったから、反対無ければ閉じようと思います
