### ISSUE TITLE
全体抽選を1ピリオドで複数回行うことを防ぐ

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#242]
Step 1: 目的
============

 * 2日め発覚：draw_allを複数回呼び出し、発表用の紙と`/checker`・DBが一致しなくなった

Step 2: 概要
============

 * `api/draw.py`で`pending`の`Application`のみを対象とする

**Comment by anharu2394** [comment]
原因はなんでしょう。

**Comment by Cj-bc** [comment]
元々、`draw_all`がタイムアウトしたら再度抽選を行うようにしてあったんだが、その間隔が短すぎて**実際はタイムアウトしていないのに**タイムアウトと判定されて複数回抽選されていた
詳しい事はあまり覚えていない（どの区間でタイムアウトしていたのかなど）けど大雑把にはそんな感じ
