### ISSUE TITLE
ensure_getenv関数の追加と現状デフォルト値を持たないos.getenvの置き換え

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#254]
現状、値のないconfig項目が存在しうる形になっていました。
それだと困るので、値がなかったら例外で死ぬようにします。
具体的には #251　のなかで言及されているものの実装になります。
現状私の手元にstashしてあるので #251がマージされ次第PRに移ろうと思います。

**Comment by shino16** [comment]
close due to inactivity
