### ISSUE TITLE
予備抽選機能の追加

### ISSUE THREAD

**Issue by anharu2394** [Sakuten/backend#255]
Step 1: 目的
============

 * 受かった人が全員来るとは限らないので、補欠合格者を作り、来なかった人の分を補います。

Step 2: 概要
============
shinoさんのdiscordから引用
> 繰り上げ当選とは、正規当選者85人に加えて繰り上げ当選を30人分設け、開演5分前の時点で正規当選者が来なかった人数分だけ先着で繰り上げ当選者を入場させることです

 * 今まで通り、85人の合格者をだす。それに加えて、補欠合格者を30人設ける。

関連するコード:
---------------
多分、このコードだと思われる
https://github.com/Sakuten/backend/blob/develop/api/draw.py

**Comment by anharu2394** [comment]
@shino-sky 詳しいことをお願いします。

**Comment by shino-sky** [comment]
- [ ] APIの検討
- [ ] DBのUserモデル変更
- [ ] configの変更
- [ ] `api.draw`に斬り込む

- [ ] wikiに解説を書く

**Comment by anharu2394** [comment]
APIの検討ってなんですか？

**Comment by shino-sky** [comment]
「補欠合格」をどう表すか（全然大した事ではないですが）
Applicationのstatus（win、lose、pending）に一つ追加すればいいと思っています

**Comment by shino-sky** [comment]
キャンセル待ちリストがwaiting listなので、waitingでいいかなと

**Comment by anharu2394** [comment]
わかりました！

**Comment by anharu2394** [comment]
@shino-sky
Userモデル変更って必要なんですか？
statusをwaitingにして、キャンセル待ちの人は表現できると思うんですけど
どういうことのために変更するんですか？

**Comment by anharu2394** [comment]
configもなにを変更すればいいんですかね
