### ISSUE TITLE
当選した次の公演の申し込み不可

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#257]
Step 1: 目的
============

 * スマホを持っている人が観劇中に申し込むということが多々あったようです。

Step 2: 概要
============

 * 当選したら、その劇を観ている想定で、次の公演には申し込めないようにします。

関連するコード:
---------------

https://github.com/Sakuten/backend/blob/develop/api/routes/api.py#L121

**Comment by shino-sky** [comment]
**昼休みに注意**

**Comment by anharu2394** [comment]
どういうことですか？

**Comment by shino-sky** [comment]
昼休み直前の公演で当選した場合は、それを観たあとに、午後で一番最初の劇に応募することができるはずということです
タイムテーブルによりますが、そこだけは直前の公演で当選していても、その次の公園に応募できるようにしないといけません

**Comment by shino-sky** [comment]
↑訂正
できません
結局かぶってます
