### ISSUE TITLE
確率変動の幅を劇の倍率によって変える

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#258]
Step 1: 目的
============

 * 5年の劇に当選すると、`win_count`が上がって6年の劇に応募するときに不利になっていました。

Step 2: 概要
============

* 低倍率のところで当選しても（普通なので）次回以降であまり不利にはなりませんが、落選するとその分（とてもアンラッキーだったので）次回以降は有利になります。
 * 高倍率のところに当選すればそれだけ次回以降不利になり、落選しても比較的有利にはなりません。

当選確率pのところに受かったら次回の当選確率がp倍、落ちたら1/p倍がふさわしいかと

関連するコード:
---------------
`api.models`、`api.draw`かな

**Comment by shino-sky** [comment]
委員会「やらない」

**Comment by shino16** [comment]
なぜか残ってたので閉じます、ごめんなさい
