### ISSUE TITLE
specが古い

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#289]
Step 1: 環境
============

 * MINGW64_NT-10.0 LAPTOP-93OTQDA5 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
 * Sakuten/devenv@89dc1f55636831784c161fd71a2e7f9e9d7ddd0e
 * Sakuten/frontend@64e6953137f2df15087e10a098bf564c95163ed5
 * Sakuten/backend@fe5f517ae83ae68136129a5bc520e56ba5e5865f
  
Step 2: 問題
============
`api/spec/`配下が時代遅れです
フロントの皆さんごめんなさい

**Comment by shino16** [comment]
重複、閉じ
