### ISSUE TITLE
GroupMemberがDBに残る

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#290]
Step 1: 環境
============

 * Microsoft Windows NT 10.0.17134.0
 * Sakuten/devenv@89dc1f55636831784c161fd71a2e7f9e9d7ddd0e
 * Sakuten/frontend@64e6953137f2df15087e10a098bf564c95163ed5
 * Sakuten/backend@cd9d1d441212ccff5bcfdc87e3a118ef28103965
  
Step 2: 問題
============

再現のための手順:
-----------------

  1. 団体応募
2. メンバーがキャンセル
  
どうなってしまうか:
-------------------

  * Applicationは削除され、`own_application`がnullのGroupMemberが残る
  
どうなるべきだったのか:
-----------------------

  * cascade delete

**Comment by shino16** [comment]
resolved
