### ISSUE TITLE
DRAWING_TIME_EXTENSIONの削除

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/backend#294]
Step 1: 目的
============

 * 2019本番で、hotfixとして中途半端に使わなくしたので、ちゃんと片付ける

**Comment by shino16** [comment]
cf. 71d0b3c072b0551d7744aaff8a55b082dcf7d514

**Comment by shino16** [comment]
そもそもこの仕様は必要ないので削除します

**Comment by shino16** [comment]
必要です…
