### ISSUE TITLE
抽選カードの漢字変換ミス

### ISSUE THREAD

**Issue by shino16** [Sakuten/backend#295]
Step 1: 環境
============

 * Microsoft Windows NT 10.0.17134.0
 * Sakuten/devenv@89dc1f55636831784c161fd71a2e7f9e9d7ddd0e
 * Sakuten/frontend@64e6953137f2df15087e10a098bf564c95163ed5
 * Sakuten/backend@3073ff3402c158e6a2562a21155e1384007f5ef5
  
Step 2: 問題
============

変換ミス
友人　有人

関連するコード:
---------------

https://github.com/Sakuten/backend/blob/develop/cards/template/cards.html.j2#L93

**Comment by OGAw-GoogleT** [comment]
https://github.com/Sakuten/backend/pull/306

**Comment by ogaw-s** [comment]
https://github.com/Sakuten/backend/pull/306
多分できました
