### ISSUE TITLE
該当時間帯において抽選を実行するスクリプトの作成(for cron)

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#3]
定期実行するために`cron`というソフトがあるのですが、
定期的に抽選を行うため、`cron`から抽選を行えなければなりません。
なので、"実行すると現時点で抽選を行う"実行ファイルを作成してください。

**Comment by Cj-bc** [comment]
`cron対応`だとcronとの連携部分のように見えて紛らわしいので、`抽選を即実行するスクリプトの作成`に変更するのはどうですか

**Comment by Cj-bc** [comment]
Todo:

- [ ]　その時間帯に該当するlottery_idを取得する
- [ ] 現在時刻から、第何回目の抽選をすればいいかを判断する
- [ ] `/lotteries`で全lotteryを引っ張ってきて、↑で判断された番号のlottery_idを引き出す
- [ ] それら全てに対して抽選を行う

**Comment by Cj-bc** [comment]
similar to #30

**Comment by coord-e** [comment]
やりますね

**Comment by coord-e** [comment]
とりあえずassignしちゃいます
front終わったら加勢する(なお
@Cj-bc

**Comment by Cj-bc** [comment]
？？？何にゃ？？？

**Comment by coord-e** [comment]
re-assign 同 #30

**Comment by coord-e** [comment]
`cron`っつか`systemd timer`かもしれないけどまあどっちにしろexecutableがいるので
てかこれ`/draw_all`殴るだけでいいんとちゃうん？つまりcurl

**Comment by coord-e** [comment]
もちろんadminの認証情報はいるが

**Comment by Cj-bc** [comment]
うん。俺もそれでいいと思う。
と言うかそうじゃなかったら`draw`関連のエンドポイントの意味がない…
なのでこのタスクはそんな重くないはず

**Comment by coord-e** [comment]
#84 Merge後でいいすか

**Comment by Cj-bc** [comment]
PR: #89

**Comment by coord-e** [comment]
#89 Merged, closing
