### ISSUE TITLE
一度に該当時間帯の抽選を行えるようにする

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#30]
`/lotteries/{lotteryId}/draw`では全部のlotteryに対してこれをやらなければいけないので、一気にできるやつを作ります
場合によっては`/lotteries/{lotteryId}/draw`を廃止すべきかもしれません

**Comment by Cj-bc** [comment]
#29

**Comment by Cj-bc** [comment]
Todo:

- [ ] 該当時間のlotteryを引っ張ってこれるようにする
- [ ] 各時間ごとに、対応するindexを保持する

**Comment by coord-e** [comment]
やるますね

**Comment by coord-e** [comment]
あっということでとりあえずよろしく
@Cj-bc

**Comment by Cj-bc** [comment]
？？？何をよろしくなのです？？？

**Comment by coord-e** [comment]
いやbackend丸投げするって言ったから一応と思ったけどフロント加勢入ったので戻す
