### ISSUE TITLE
QRコードPDF作成

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#32]
#31 IDリストから印刷用のPDFを作成する

**Comment by coord-e** [comment]
QRコードだけでなく確認用IDも印刷しないといけない

**Comment by Cj-bc** [comment]
これQRの中身ってどうします？
URL,etc...

フロントとも合わせなきゃなので地味にbackendだけじゃ動けないなこれ...

**Comment by Cj-bc** [comment]
URLは未確定なので、
`指定された文字列をQRコードに加工し、PDFに出力する`
コードを書きます。

**Comment by Cj-bc** [comment]
PDFよりも、HTMLの方が楽そうなので、
`Python -> HTML出力 -> html2pdfでPDFに加工`
という手順をとります

**Comment by Cj-bc** [comment]
Task

### QR作成パート
- [ ] Private IDを取得する
- [ ] URLを生成する
- [ ] QRコードを出力する

### cardオブジェクト
- [ ] QRコードのpathを取得する
- [ ] Public IDを取得する

- [ ] cardオブジェクトのlistを取得する
- [ ] render()でレンダリングする
- [ ] PDFを出力する

**Comment by Cj-bc** [comment]
ワンコマンド実行したらPDFが作れる、って感じで作りますね

**Comment by Cj-bc** [comment]
# Dep tree

Execute -- `do.sh`
                     |---- `mkqr.py`
                     |            |-----  `ids.json` (Secret IDとPublic IDのリストを保持するファイル)
                     |
                     |---- `mkhtml.py`
                     |           |--------  `card.py`
                     |           |--------  `ids.json` (Secret IDとPublic IDのリストを保持するファイル)
                     |           |--------  `cards.html.j2
                     |
                     |---- `html2pdf`
                                |-------- `cards.html` (`mkhtml`で作られたもの)

**Comment by Cj-bc** [comment]
違う...そうじゃない...
<img width="1401" alt="2018-07-23 17 41 08" src="https://user-images.githubusercontent.com/16875061/43066517-d5c77bb0-8e9f-11e8-8f85-d2e8d9eb818d.png">

**Comment by Cj-bc** [comment]
HTMLまでは大体ができたのですが、これからスタイルの調整があります。
また、地味にIDが最初から貼られていない(2からになっている)ので1からになるように調整します

**Comment by Cj-bc** [comment]
該当Branch: feature/32-make-qr-pdf
