### ISSUE TITLE
当選者張り出し用PDF作成

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#36]
確認用IDを並べる
pdfを返すエンドポイントとかあってもいいかもしれない

**Comment by Cj-bc** [comment]
運営用のアカウントを作成、それ以外のアカウントからのアクセスを禁止して使うとかそんな感じ？
寧ろ既存のAPIをshellscriptで叩いてpandocとかで出力させた方が楽じゃないか？それをワンクリでやるor誰かがいるすればいいので。そしたら印刷まで自動化できるし

**Comment by coord-e** [comment]
そうだね、
まあそれもいいけど生徒会が印刷するだろうからあんまりそこに技術を噛ませたくないのがある

**Comment by coord-e** [comment]
会室のプリンターって自動化できるレベルのそれがあるんか(USBメモリ経由でしかできないイメージ)
技術者じゃなくても、ここにアクセスすれば結果が出るよー印刷してねーってできるようにしたいのがある

**Comment by Cj-bc** [comment]
えだって`lpr`使えばよくない？？
ドライバさえ入ってれば問題なく動くぜ。USB経由だし。
...あでもでかい方の印刷機だとわからんのかな、向こうはよくわからんです。
少なくとも小型プリンタは`lpr`で印刷したことあるが。

ちなみに僕としては、時間になったら`cron`で自動的にデータ取って来て`shellscript`であれやこれやして`lpr`で印刷かけるイメージだった。

まぁどちらにせよ確認用IDで返すAPIは要るか

**Comment by coord-e** [comment]
まあそれは理想やな(僕が想像していたのはでかい方)
紙のサイズについて委員会と話し合わぬと

**Comment by Cj-bc** [comment]
プロジェクタで投影するかもしれないとのことなので、このissueは適切ではない...?
当選者IDの一覧を返すAPIの作成として新たに立て直した方がいいと思うので、一度閉じます

**Comment by Cj-bc** [comment]
new issue here -> #50
