### ISSUE TITLE
複数人まとめて応募、抽選の実装

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#37]
代表者で抽選し、その結果に倣う。
何人まで同時に応募可能かは検討中

**Comment by Cj-bc** [comment]
団体応募の人数は**4人**がmaxになりました

**Comment by Cj-bc** [comment]
これ、抽選と応募をissue若田ほうがいい気がします。
これ一個だととても重い...

**Comment by Cj-bc** [comment]
フローの整理

ユーザー：
 1. 1人の端末から普通にログイン
 2. 応募フォームに移る
 3. 応募人数をBoxか何かで決定する
 4. 確定ボタン（的なもの）を押下

ちょっと待ってこれUML書いたほうがいい気がして来た

**Comment by Cj-bc** [comment]
```plantuml

@startuml

actor user
activate frontend
activate backend

user -> user : 端末からログイン
user -> user : 応募フォームに移る
user -> user : 応募人数をboxか何かで決定する
user -> frontend : 確定ボタン（的なもの）を押下

frontend -> frontend : ユーザーの入力を取得・送信

backend -> backend : 認証等
backend -> backend : 

```

**Comment by Cj-bc** [comment]
そもそもこれの仕様を決める必要があります。
リクエストの形も変わるので...

**Comment by Cj-bc** [comment]
- [ ] 代表者を1人とみなすか、複数人とみなすか
- [ ] 抽選の際の当選確率の上下
- [ ] それぞれのユーザーにapplicationを作成するのか？
- [ ] Applicationモデルの変更（人数・同時に応募している人を格納しなければならないから）
- [ ] `WINNERS_NUM`を、複数人応募の状況に合わせて変更可能にする

**Comment by Cj-bc** [comment]
個人的な意見書いていきます

> それぞれのユーザーにapplicationを作成するのか？
作るべきだと思います。なぜなら、各ユーザーにapplicationを作成しなかった場合、抽選フローが難しくなってしまうからです。...いや、どちらにしろ難しいんですが...
というか結構複数人抽選不利になる予感
作らなかった場合：
```
1. 当選人数が90人以下に設定されます（複数人応募当選の可能性を踏まえて）
2. 抽選が行われます
3. 抽選の結果
 3.1 複数人応募の人がいた場合 →　その分の人数が加算され、90人に満たなければその分再度引き直し（ただしこれも複数人応募当選の可能性を踏まえて少なめに）　このループを90人になるまで続ける
 3.2 複数人応募の人がいなかった場合 →　念のために空けておいた枠でまた抽選を行う。ただしこれも(ry)で人数少なめに行う　またこれもループ
```

各人にapplicationを作成した場合：
```
1. 全体から90人抽選を行う
2. その中から、複数人応募をしている人がいるか探す
3. 居た場合、その応募した人数が全員当選しているか探す。全員当選して居なければ落選扱いに変える
4. それで空いた分をまた抽選する
```
後者の方がシンプルではある。
これもなかなかに理不尽なシステムなので誰かいい案思い付いたら投げて...

> Applicationモデルの変更（人数・同時に応募している人を格納しなければならないから）
まぁこれは必須ですね。

現状：
```
{
  "id" : int
  "status" "pending"|"won"|"lose"
  "lottery":
    {
      lottery_data
    }
```
追加：
```
{
  "id" : int,
  "status" "pending"|"won"|"lose",
  "group":
    [
       "secret_id": secret_id,
       "secret_id": secret_id
    ],
  "lottery":
    {
      lottery_data
    }
```

**Comment by tamazasa** [comment]
>それぞれのユーザーにapplicationを作成するのか？
僕も作るべきだと思います

思いついたアルゴリズム：

1. `applications/`から複数人で応募した人を探す
2. そのグループの[代表者の当選確率|各確率の平均|確率の最低値]で１人のみ抽選を行う
（確率変動はv0.3なので、v0.2の段階ではとりあえず`90/len(applications)`を確率とし、
`random.random() < probability`で当選か否かを決定）
3. 当選した場合、グループ全員を当選
落選した場合、グループ全員を落選
4. `WINNERS_NUM`から3. の当選者の数を引き、複数人応募していない残りの人で抽選する

**Comment by tamazasa** [comment]
僕が考えていたのは、
`is_rep`でがリーダーだけ`True`になっていて、
`True`の人を順番に抽選処理していく感じです
当選だったら、`group_members`の人々を全員当選っていうのを考えてました

**Comment by Cj-bc** [comment]
なるほど！
わかりやすい。とてもいいと思います...

その場合、グループの各メンバーの`application`について二つ意見があります。

### 一つ目
#### *最初の時点では*(重要)作成しないほうが良いのではないか
作成する場合、グループ登録であることがわかるように何か値を持たせないかぎり、1人での応募（以下一般応募とする）と見分けがつかなくて一般応募の抽選回すときに含まれてしまいそうだから...

ただこれ`application`作らない弊害として、各クラスにいる担当の委員の人がチェックするフローが（システム的に）ちょっとだけ複雑になりそうってのがあります。
具体的には、一般応募やグループ応募の代表者は`application`を拾ってくればいい為変わりはありません。ですがグループ応募のメンバーは`application`がないため、代表者の`application`を見に行ってそこの`group_members`を見て..という手順を取らなくてはならなくなると思います。
解決策としては、`当選した時にapplicationを制作する`のがいいかなと思っています。
ただこれは技術的宗教観といいますか、意見の分かれるところだと思うので（特に @coord-e ）どうなんだろうなぁという気持ちでいます。

### 二つ目

#### 各グループメンバーの`application`は作成するが、メンバーであることを示すbool値を入れる。

これは一つ目の方で書いた、

> グループ登録であることがわかるように何か値を持たせないかぎり、1人での応募（以下一般応募とする）と見分けがつかなくて一般応募の抽選回すときに含まれてしまいそうだから...

の解決策を採用するものです。
こっちの方が軽く済む気もするけど...どうなんだろうか...

**Comment by tamazasa** [comment]
グループ側の抽選が終わった後、`status`を全部`won`と`lose`にして、
一般応募で残りの`pending`をさばくのをイメージしてました

**Comment by Cj-bc** [comment]
なるほど！
それならどっちもやらずに済む...いいね 👍 
~~なんだよ私考えなくってよかったやんけマジで頭いいな！？~~
じゃあ、まとめるとこんな感じですかね？

---

`application`に以下を追加；
```yaml
is_rep (bool): 代表者の確率で抽選するときに必要
               これを複数人応募のグループを見分けるグループID代わりに利用する
group_members (list): 他のメンバーのID
                      代表者だけ保持していれば十分
```

団体応募プロトコル：
```markdown
1. 団体代表者でログインする
2. クラスを選択し、応募人数を決定する
3. 送信
4. (鯖サイド) 団体代表者のapplicationを作成
5. (鯖サイド) *代表者のapplication*の`is_rep`を`True`に設定し`group_members`に他の団体応募メンバーのuser_idを格納
6. (鯖サイド) 他のメンバーのapplicationを作成
```

抽選プロトコル：
```markdown
1. 対象のLotteryの`application`を全て取得する
2. そのうち`is_rep`が`True`の`application`を取得する
3. *以下抽選アルゴリズム*を用いて、2.で取り出した各`application`に対し当選・落選を判定
4. 当選した`application`の`status`に`won`を設定
5. 当選した`application`の`group_members`からメンバーの`user_id`を取得し、その`application`の`status`を`won`に設定
6. 落選した`application`の`status`についても同様に`lose`を設定する
7. **1.**の`application`から、`status=pending`のものを取得する
8. **7.**に対し`WINNERS_NUM`から`status=won`の数だけ引いた値で`random.choice()`をまわす
9. **8.**の結果を各`application`の`status`に反映する
```

抽選アルゴリズム：
```markdown
以下引用
> そのグループの[代表者の当選確率|各メンバーの確率の平均|確率の最低値]で１人のみ抽選を行う
（確率変動はv0.3なので、v0.2の段階ではとりあえず90/len(lotteries)を確率とし、
random.random() < probabilityで当選か否かを決定）
```

**Comment by tamazasa** [comment]
いいと思います

**Comment by tamazasa** [comment]
実装の都合上、`group_members`の保持するIDを
`secret_id`の代わりに、データベースの`User`テーブルが持つ`id`にしました

**Comment by tamazasa** [comment]
さきほどのCj-bcさんのコメントと同じですが一応

**Comment by Cj-bc** [comment]
separate into #115 #116

**Comment by Cj-bc** [comment]
close with #115 , #116
