### ISSUE TITLE
当選者発表用API`/classrooms/{id}/winners`の追加

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#50]
### Step 1: 目的

 * 当選者IDを発表するために、当選者IDを返すAPIが必要です。

### Step 2: 概要

 * 現状では、紙の張り出しかプロジェクタでの発表かわからないので、純粋に当選者IDを返すAPIが必要と考えています。

### タスク:

- [x] 新たなエンドポイントの策定 -> `/classrooms/{id}/winners`になりました
- [x] エンドポイントの実装

**Comment by Cj-bc** [comment]
Issue #36 から新規作成されました

**Comment by Cj-bc** [comment]
#29 にてエンドポイントを策定、その後対応になると思います

**Comment by Cj-bc** [comment]
#29 がPRまでいったので続きやります

**Comment by Cj-bc** [comment]
当選者の確認用IDの配列のみ返すでいいですよね？

**Comment by Cj-bc** [comment]
#decision より、このAPIを使用するための権限は特に設定しません。
一応確認です。
@Sakuten/moderator

**Comment by Cj-bc** [comment]
これ、よく考えたら マイルストーン v0.3で余裕があるので、一度Assign外れて違うもの進めます。
後にまだ残っていれば引き継ぎます。

**Comment by Cj-bc** [comment]
feature/50-add-winners-apiブランチで作業を進めてたので、もしよければ使ってください

**Comment by tamazasa** [comment]
これタイトルは`/classrooms/{id}/winners`になってますが
作業中のブランチ見ると`/lotteries/{id}/winners`になってました
これは前者が正しいということで良いのでしょうか

**Comment by tamazasa** [comment]
feature/50-add-winners-apiブランチはこちらの方でも`/lotteries`のまま作業を勧めてしまったので
Cjさんが作ったものにいくらか追加されてます

**Comment by Cj-bc** [comment]
ん〜...どうだっただろうか...
一応APIの意味合い的には`/lotteries`の方が正しい気がする（そのlotteryの勝者ということなので）のだがとりあえずdiscord確認しなおしてみる。

**Comment by tamazasa** [comment]
cj.BC_SD: まぁ簡潔にまとめると？
* /lotteries/{id}/winnersで返すのは、当選者の全情報かそれともpublic_idだけのリストか
ってとこが主な発端で
@coord.e#9043 の主張としては /lotteries/{lottery_id}/winners/{ID}をフィルターとして働かせたくて、そのために/lotteries/{lottery_id}/winnersは当選者の全情報を返す。
@cj.BC_SD#4033 の主張としては/lotteries/{lottery_id}/winnersで必要とされているのはpublic_idのリストだけなのだからそれだけ返せば良い

あとあった問題が
* /lotteries/{lottery_id}/winners/{ID}でそのIDが当選者であるかどうかの確認ができることにする。この{ID}は何にするか(public_id, secret_id, id)

**Comment by tamazasa** [comment]
↑7/17の #api-spec チャンネルにありました

**Comment by Cj-bc** [comment]
うん、純粋に考えるとそれが一番新しいコメントなので`/lotteries`かなぁって気がしている
ちなみに`/classroom`の記述は7/15が最後かな？

**Comment by tamazasa** [comment]
そうですね
僕も`lotteries`で返すのが筋であるように感じますし
それでいいですよね

**Comment by coord-e** [comment]
いいと思います

**Comment by Cj-bc** [comment]
close with marging of #131
