### ISSUE TITLE
auth_errorの構文について

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#55]
[api/auth.py login_required内 L65](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L65)において、`auth_error`の引数として`realm`を使っているがそのほかの場所、例えば:
[api/auth.py login_required内 L68](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L68)
[api/auth.py login_required内 L70](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L70)
[api/auth.py login_required内 L72](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L72)
[api/auth.py login_required内 L76](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L76)
[api/auth.py login_required内 L79](https://github.com/Sakuten/backend/blob/8f35d892d2da3b30e0fc0c0fbf570f7ad62765de/api/auth.py#L79)

では`realm`を使わずに`error`を使っています。
中のコードを見るに、これではその引数の値が使われていないのではないかと推測します...
なので、全部realmにするなど考えているのですがどうでしょうか。それとも何か意図があったのか...??
@coord-e

**Comment by Cj-bc** [comment]
つまり、`error=`の部分も含めて渡している、ということです？

**Comment by coord-e** [comment]
`realm`はMAY
