### ISSUE TITLE
`/classrooms`を`sort`に対応させる

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#60]
Step 1: 目的
============

 * [仕様](https://sakuten-api-spec.now.sh/#/lottery/getClassrooms)に準拠するため

Step 2: 概要
============

 * `/classrooms?sort=grade`等に対応できるようにする

関連するコード:
---------------

参考になりそうなもの:

https://gist.github.com/kwatch/fe96d6c13cd3c7d12c89

タスク:
=======

- [ ] `classrooms`に、動的なsortをかける

**Comment by Cj-bc** [comment]
#56 merge後作業

**Comment by tamazasa** [comment]
今更ながら：
この仕様どう使うんですか？

**Comment by Cj-bc** [comment]
あこれな、こーでぃがとりあえずつけただけ（API仕様としてつけたかったらしい）なので使うかどうかわからんやつ（というか使う見込みはないから作らんでもいいやつよ...）

**Comment by Cj-bc** [comment]
#59  #62 #63 も同じく現状作らなくて大丈夫なやつっすorz
