### ISSUE TITLE
`/applications`エンドポイント群の追加

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#65]
Step 1: 目的
============

 * [仕様書](https://sakuten-api-spec.now.sh)に合わせる必要があります。

Step 2: 概要
============

 追加するエンドポイントは以下の通りです

* `/applications` -- 全てのapplication(応募)を返します
* `/applications/{application_id}` -- 指定されたapplicationの情報を返します
* `/applications/{application_id} [DELETE]` -- 指定されたapplicationを削除します。HTTP methodはDELETEです。

タスク:
=======

- [x] `/applications`の権限を確認する（現状では権限の縛りがないが、仕様の中では403を返すので縛りはあるべきなのだと思う)

**Comment by Cj-bc** [comment]
#56 merge後作業

**Comment by coord-e** [comment]
シュッと

**Comment by coord-e** [comment]
やった
タスクについて、403はadmin/checkerなので別Issueで対応
