### ISSUE TITLE
`/lotteries/{id} [POST]`に、403ステータスコードを追加する

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#67]
Step 1: 目的
============

 * [仕様書](https://sakuten-api-spec.now.sh/#/lottery/applyLotteryById)によると、このエンドポイントは403を返すようになっていますが現実装ではそうなっていません。
* この403は、`admin`や、各クラスでの受付を行う`staff`用の権限の場合に返すことになると考えています。

Step 2: 概要
============

* 権限を持たないtokenでアクセスが来た場合、403を返す

**Comment by Cj-bc** [comment]
#56　merge後に作業

**Comment by tamazasa** [comment]
#98 のmergeにより解決
