### ISSUE TITLE
エラーをレスポンスから隠す

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#7]
`flask initdb`する前にリクエスト飛ばしたらこんな感じになりました。
内部の色々を晒しているので非常によくないです。
initdb忘れに限らず、Python側の内部エラーがレスポンスに紛れ込まないようにしなければなりません。

<img width="1199" alt="2018-05-31 21 27 45" src="https://user-images.githubusercontent.com/16184855/40785117-94e138a8-6522-11e8-802b-89697a132740.png">

**Comment by coord-e** [comment]
flaskのデバッグ機能かもしれません(だったら安心)
調査します

**Comment by Cj-bc** [comment]
これは...結局バグだったんでしょうかそれともデバッグ機能だった...???

**Comment by coord-e** [comment]
これ、flaskのデバッグでした
