### ISSUE TITLE
#30 - /draw_allと/lotteries/{idx}/drawのNobodyIsApplyingError挙動の違い

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#80]
Step 1: 環境
============

 * OS: Linux coordiserver 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
 * devenv: 90569b09bf78e0d93eff82eb8aff941774adc111
 * frontend: 9fff780f52b57e311d2e950869904869ce1f572e
 * backend: b5253cfe9761029cd2dd3e915e3cfcedfc001ea2
  
Step 2: 問題
============

再現のための手順:
-----------------

(再現するものではないが)
#30 に該当するPRについて。(またはそれがマージされた後の世界)
便宜上エンドポイントで表記したがどちらかというと`api.draw.draw_one`と`api.draw.draw_at_index`の問題。

どうなってしまうか:
-------------------

  * `api.draw.draw_at_index`では`NobodyIsApplyingError`発生時、対象`lotteries`が全て`done=True`になっている
  * 一方`api.draw.draw_one`では`NobodyIsApplyingError`発生時、`done=False`
  * 挙動が紛らわしく混乱を招く
  * `NobodyIsApplyingError`は、「誰も応募していないのに引いちゃうんですか？」的ストッパーの意図だったが、意味論としては問答無用で引くべきだったかもしれない。

どうなるべきだったのか:
-----------------------

選択肢
  1. `NobodyIsApplyingError`をやめる。誰もいなかったら空。そして`done=True`
  2. `api.draw.draw_one`で、`NobodyIsApplyingError`発生時、`done=True`にする

個人的に2は感覚にそぐわないので1かなと

**Comment by Cj-bc** [comment]
現実問題として、(ないだろうけど)仮に誰もいなくても抽選は行う必要があり、かつcronで自動化してしまうので**間違って時間前に回してしまう**ということはないと考えられますね。
なので、Error排除→`done=True`の1番でいいと思いますでいいと思います。

**Comment by coord-e** [comment]
はい
