### ISSUE TITLE
test_trailing_slashのテストしているURLが違う

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#87]
Step 2: 問題
============

問題点:
-------------------

  * [test/test_misk.py](https://github.com/Sakuten/backend/blob/develop/test/test_misc.py)の`test_trailing_slash`のURLが違う気がする
  
現状のコード:
-----------------------

```python
    resp = client.get('/api/classrooms', follow_redirects=False)
    resp_with_slash = client.get('/api/classrooms/', follow_redirects=False)
```

本来:
-----------------------

```python
    resp = client.get('/classrooms', follow_redirects=False)
    resp_with_slash = client.get('/classrooms/', follow_redirects=False)
```

**Comment by coord-e** [comment]
うーん、テストの趣旨として間違ってはいないがこのままだと気持ち悪いね

**Comment by Cj-bc** [comment]
え、そもそもこれなんで動いてるの…？
`/api/`なんて無いのに
だからテスト失敗してないかな？？と思ったりした

**Comment by coord-e** [comment]
いやステータスがリダイレクトではなく、レスポンスが一致してれば通るのでどちらも404で同じエラー返して通る

**Comment by Cj-bc** [comment]
あ、そうか
とりあえずやっぱりテストは壊れてますよね...
直さないと意味がない

**Comment by coord-e** [comment]
意味はある、もしリダイレクトが有効になってたらこれは302で落ちる。。
ただし404に対してテストするのもなんかなあっていう感じがするので。

**Comment by Cj-bc** [comment]
ホォ？
まぁ知らんが直すでいいんだな？

**Comment by coord-e** [comment]
うん

**Comment by Cj-bc** [comment]
close by merging #112
