### ISSUE TITLE
`/lotteries/{id} [POST]`に、二度目以降のリクエストに対するエラーを追加する

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#93]
Step 1: 目的
============

Step 2: 概要
============

 * 具体的には、status_codeを400にします。
 * error messageはこれから決めてください

関連するコード:
---------------

  ```
  // TODO(you): code here to reproduce the problem
  ```
タスク:
=======

- [ ]  error messageを決めてください
- [ ] 
- [ ]

**Comment by tamazasa** [comment]
error messageでぱっと思いついたやつ：
`multiple requests in one lottery`

**Comment by Cj-bc** [comment]
1個目の解釈で合っています。
同じ`lottery_id`=`同じクラスの同じ時間帯`に複数回応募するのがだめということです。
以前そのクラスに当選してるか否かは関係ないです〜

一応補足しておくと、これは`POST`メゾットはユーザーからのデータをもとにリソースを作成するメゾットであり、複数回リクエストすると同じデータで同じリソースを作ることになるためエラーを吐く必要がある、ということです。
詳しくはDiscordのbackendかapi-specで話し合った痕跡があるはず（結構前）なので気になったら調べてください。もしくは聞いてください。~~答えられるかはともかく~~
